--- # Installation of packages
- hosts: chefserver
  user: chef
  become: yes
  connection: ssh
  vars:
          pkgname: git
  tasks:
          - name: insall git package
            action: yum name = '{{pkgname}}' state = install
